# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EusxNQiWc-eiZ7oA3MAitjZGS1m-W3Uw
"""

import streamlit as st
import geopandas as gpd
import pandas as pd
# Import the engine logic
from engine_layer_py import run_analysis, calculate_priority_recommendations

st.title("Kaduna Health Decision Support System")

# --- PHASE 1: INPUT LAYER ---
st.sidebar.header("1. Upload Input Data")
outpatient_file = st.sidebar.file_uploader("Outpatient Excel", type=['xlsx'])
health_facilities_file = st.sidebar.file_uploader("Health Facilities (Zip)", type=['zip'])
lga_boundary_file = st.sidebar.file_uploader("LGA Boundaries (Zip)", type=['zip'])
roads_file = st.sidebar.file_uploader("Road Network (Geopackage)", type=['gpkg'])

# --- PHASE 2: ENGINE TRIGGER ---
if st.sidebar.button("Run Full System Analysis"):
    if outpatient_file and health_facilities_file and lga_boundary_file:
        # Load data into GeoDataFrames
        facilities = gpd.read_file(health_facilities_file)
        lga_bounds = gpd.read_file(lga_boundary_file)

        # Run the processing engine
        st.write("Processing Spatial Data... Please wait.")
        # priority_df and sites are generated here
        priority_df, sites = calculate_priority_recommendations(lga_bounds, healthcare_deserts)

        # --- PHASE 3: PRIORITY DASHBOARD ---
        st.header("📍 Strategic Resource Allocation")
        st.subheader("I. LGA Priority Ranking")
        st.dataframe(priority_df, use_container_width=True)

        st.subheader("II. Suggested GPS Locations (30km Spacing)")
        st.table(pd.DataFrame(sites))

        # (Add your Map plotting code here)
    else:
        st.error("Please upload all required files in the sidebar.")

st.title("Kaduna Health Decision Support System")
uploaded_file = st.sidebar.file_uploader("Upload Health Data", type=['xlsx', 'shp', 'zip'])

if st.button("Run Analysis"):
    priority_df, sites = calculate_priority_recommendations(data)
    st.dataframe(priority_df)